### ISSUE TITLE
JWT nicht kopierbar im Chrome Browser

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-frontend#32]
Ich nutze Chrome Version 100.0.4896.127. Wenn ich bei "Special Users" auf "Gen. JWT" klicke, öffnet sich zwar ein Hinweisfeld, allerdings ist das JWT daraus nicht kopierbar. Bei Firefox kann ich den Inhalt markieren und kopieren. 

Vielleicht eignet sich eine andere Anzeigeart besser?

**Comment by moebiusband73** [comment]
Transferred to https://github.com/ClusterCockpit/cc-backend/issues/15
