### ISSUE TITLE
Make appearance of plots configurable

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-frontend#6]
The configuration will be provided server-side.

**Comment by iamlouk** [comment]
A lot of work on this has been done while developing the frontend in [PHP ClusterCockpit](https://github.com/ClusterCockpit/ClusterCockpit).

The only thing still missing for cc-backend/cc-frontend is a UI that allows users to change configuration values such as `plot_general_lineWidth`, `plot_general_colorscheme`, `plot_general_colorBackground`. The non-`plot_general` configurations, such as the metrics shown in a datatable etc., can all already be changed on the respective pages.

Any ideas?
